---
#-------------------------------
# General Site Settings
title: Ethereum Venture Studio | BlockEquity
logo: /images/logo.png # You can add own logo. For example '/images/logo.png'.
tagline: Ethereum Dev Shop & Dapp Marketing Agency
description: Ethereum education, tutorials, and breakdowns of the next frontier of the internet - Web3 and the Ethereum super computer.
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://www.blockequity.com" # The base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# Author Settings
author:
  name: digital3000
  avatar: "/images/3k.jpg"

#-------------------------------
# Hero Settings
hero:
  title: Ethereum Studio
  description: News, Tutorials, Marketing, & Teardowns
  image: "/images/cover.jpg"

#-------------------------------
# Contact Settings
contact:
  email: blockequity@gmail.com # Add your email for contact form
  description: Hey! We're glad you stopped by, if you need to get in touch with us for any reason, just fill out the form below and we'll be in contact within 24 hours. # Add a description of your form

# NOTE
# Aditu theme comes with a contact form built-in. You can use this form with Formspree service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.

#-------------------------------
# Footer section
# Example of adding a new link to the footer - {icon: "ion-logo-github", link: "https://github.com"}
# Other icons can be found at https://ionicons.com
social:
  - { icon: "ion-logo-twitter", link: "https://twitter.com/block_equity" }
  - { icon: "ion ion-logo-github", link: "https://github.com/blockequity" }

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: blockequity # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Google Analytics
# google-analytics: GTM-T654QLL # Add your identifier. For example UA-99631805-1.
google:
  tag_manager:
    container_id: GTM-T654QLL

#-------------------------------
# Newsletter
mailchimp: true # To enable the mailchimp form, use the value true. To turn off use the value false.
mailchimp-identifier: blockequity.us7.list-manage.com/subscribe/post?u=a89c1803c6cd4103e90b4340c&amp;id=d2bcba6e8a # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

#-------------------------------
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-seo-tag

paginate: 9
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: "_pages"
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: pretty

sass:
  sass_dir: _sass
  style: compressed

# Twitter Schema
twitter:
  username: block_equity
  card: summary
